[package]
name = "kv-lake-cli"
version = "0.1.0"
authors = ["Akshay Takkar <akshayt@m3india.in>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
